#!/usr/bin/env bash
#print Best school using while loop until #9

count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best school"
    (( count++ ))
done
