#!/usr/bin/env bash
#this will do a bunch of stuff
#you should be able to analyse the code
#and figure it out

count=1

while [ $count -le 20 ]
do
    echo "%count"
    case $count in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( count++ ))
done
