#!/usr/bin/env bash
#configure the firewall to block incoming traffic
#except for these ports 80, 443, 22
#ufw is Uncomplicated Firewall

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
